const dayjs = require('dayjs');

const dataType = require('../../constats/dataType');
const inputType = require('../../constats/inputType');
const datetimeFormat = require('../../constats/datetimeFormat');
const moduleId = require('../../constats/moduleId');

const now = dayjs().format(datetimeFormat.datetime.value);

module.exports = [
    {
        moduleId: moduleId.fields,
        name: 'id',
        label: 'ID',
        inputType: inputType.number,
        dataType: dataType.integer,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: true,
        notNull: true,
        unique: true,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'moduleId',
        label: 'Module ID',
        inputType: inputType.dropdown,
        dataType: dataType.integer,
        tableRef: 'Modules',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'name',
        label: 'Name',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'label',
        label: 'Label',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'inputType',
        label: 'Input Type',
        inputType: inputType.dropdown,
        dataType: dataType.integer,
        tableRef: 'InputTypes',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'inputType',
        label: 'Input Type',
        inputType: inputType.dropdown,
        dataType: dataType.integer,
        tableRef: 'DataTypes',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'tableRef',
        label: 'Table Ref',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'tableRefKey',
        label: 'Table Ref Key',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'tableRefName',
        label: 'Table Ref Name',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'tableRefAlias',
        label: 'Table Ref Alias',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'tableRefFilter',
        label: 'Table Ref Filter',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'regex',
        label: 'Regex',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'multiSelect',
        label: 'Multi Select',
        inputType: inputType.toggle,
        dataType: dataType.boolean,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'identity',
        label: 'Identity',
        inputType: inputType.toggle,
        dataType: dataType.boolean,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'notNull',
        label: 'Not Null',
        inputType: inputType.toggle,
        dataType: dataType.boolean,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'unique',
        label: 'Unique',
        inputType: inputType.toggle,
        dataType: dataType.boolean,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'autoIncrement',
        label: 'Auto Increment',
        inputType: inputType.toggle,
        dataType: dataType.boolean,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.fields,
        name: 'sequence',
        label: 'Sequence',
        inputType: inputType.number,
        dataType: dataType.integer,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: false,
        unique: false,
        createdAt: now,
        updatedAt: now,
    },
];
