const dayjs = require('dayjs');

const dataType = require('../../constats/dataType');
const inputType = require('../../constats/inputType');
const datetimeFormat = require('../../constats/datetimeFormat');
const moduleId = require('../../constats/moduleId');

const now = dayjs().format(datetimeFormat.datetime.value);

module.exports = [
    {
        moduleId: moduleId.users,
        name: 'id',
        label: 'ID',
        inputType: inputType.number,
        dataType: dataType.integer,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: true,
        notNull: true,
        unique: true,
        sequence: 1,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.users,
        name: 'name',
        label: 'Name',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 2,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.users,
        name: 'email',
        label: 'Email',
        inputType: inputType.shortText,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: true,
        sequence: 3,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.users,
        name: 'password',
        label: 'Password',
        inputType: inputType.password,
        dataType: dataType.varchar,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 4,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.users,
        name: 'roleId',
        label: 'Role ID',
        inputType: inputType.dropdown,
        dataType: dataType.integer,
        tableRef: 'Roles',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 5,
        createdAt: now,
        updatedAt: now,
    },
];
