const dayjs = require('dayjs');

const dataType = require('../../constats/dataType');
const inputType = require('../../constats/inputType');
const datetimeFormat = require('../../constats/datetimeFormat');
const moduleId = require('../../constats/moduleId');

const now = dayjs().format(datetimeFormat.datetime.value);

module.exports = [
    {
        moduleId: moduleId.validations,
        name: 'id',
        label: 'ID',
        inputType: inputType.number,
        dataType: dataType.integer,
        tableRef: null,
        tableRefKey: null,
        tableRefName: null,
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: true,
        notNull: true,
        unique: true,
        sequence: 1,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.validations,
        name: 'moduleId',
        label: 'Module ID',
        inputType: inputType.dropdown,
        dataType: dataType.tableReference,
        tableRef: 'Modules',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 2,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.validations,
        name: 'actionId',
        label: 'Action ID',
        inputType: inputType.dropdown,
        dataType: dataType.tableReference,
        tableRef: 'Actions',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 3,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.validations,
        name: 'scriptId',
        label: 'Script ID',
        inputType: inputType.dropdown,
        dataType: dataType.tableReference,
        tableRef: 'Scripts',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 4,
        createdAt: now,
        updatedAt: now,
    },
    {
        moduleId: moduleId.validations,
        name: 'validationTimeId',
        label: 'validation Time ID',
        inputType: inputType.dropdown,
        dataType: dataType.tableReference,
        tableRef: 'ValidationTimes',
        tableRefKey: 'id',
        tableRefName: 'label',
        tableRefAlias: null,
        tableRefFilter: null,
        regex: null,
        multiSelect: false,
        identity: false,
        notNull: true,
        unique: false,
        sequence: 5,
        createdAt: now,
        updatedAt: now,
    },
];
