module.exports = {
    shortText: 1,
    longText: 2,
    dropdown: 3,
    number: 4,
    toggle: 5,
    date: 6,
    time: 7,
    file: 8,
    richText: 9,
    radio: 10,
    checkbox: 11,
    code: 12,
    datetime: 13,
    password: 14,
};
