module.exports = {
    access: 13,
    actions: 12,
    dataTypes: 4,
    fields: 5,
    files: 6,
    inputTypes: 3,
    logError: 16,
    menus: 8,
    modules: 1,
    roles: 2,
    scripts: 11,
    tokens: 10,
    users: 9,
    validations: 15,
    validationTimes: 14,
    views: 7,
};
