module.exports = {
    access: 24,
    actions: 19,
    dataTypes: 4,
    fields: 5,
    filed: 25,
    inputTypes: 3,
    logError: 27,
    menus: 7,
    modules: 1,
    roles: 2,
    scripts: 18,
    tokens: 9,
    users: 8,
    validations: 21,
    validationTimes: 20,
    views: 6,
};
