module.exports = {
    modules: 1,
    roles: 2,
    inputTypes: 3,
    dataTypes: 4,
    fields: 5,
    views: 6,
    menus: 7,
    users: 8,
    tokens: 9,
    script: 18,
    actions: 19,
    validationTime: 20,
    validation: 21,
    logError: 27,
};
