module.exports = {
  modules: 1,
  roles: 2,
  inputTypes: 3,
  dataTypes: 4,
  fields: 5,
  files: 6,
  views: 7,
  menus: 8,
  users: 9,
  scripts: 10,
  actions: 11,
  access: 12,
  validationtimes: 13,
  validations: 14,
  logError: 15,
  jsReportDataSchema: 16,
};
