'use strict';

const dayjs = require('dayjs');

const dataType = require('../constats/dataType');
const inputType = require('../constats/inputType');
const datetimeFormat = require('../constats/datetimeFormat');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface) {
        /**
         * Add seed commands here.
         *
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   name: 'John Doe',
         *   isBetaMember: false
         * }], {});
         */
        const now = dayjs().format(datetimeFormat.datetime);

        await queryInterface.bulkInsert(
            'Fields',
            [
                {
                    moduleId: 1,
                    name: 'id',
                    label: 'ID',
                    inputType: inputType.number,
                    dataType: dataType.integer,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: true,
                    notNull: true,
                    unique: true,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 1,
                    name: 'moduleId',
                    label: 'Module ID',
                    inputType: inputType.dropdown,
                    dataType: dataType.tableReference,
                    tableRef: 'Modules',
                    tableRefKey: 'id',
                    tableRefName: 'name',
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: true,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 1,
                    name: 'content',
                    label: 'Content',
                    inputType: inputType.code,
                    dataType: dataType.json,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: false,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 2,
                    name: 'id',
                    label: 'ID',
                    inputType: inputType.number,
                    dataType: dataType.integer,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: true,
                    notNull: true,
                    unique: true,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 2,
                    name: 'name',
                    label: 'Name',
                    inputType: inputType.shortText,
                    dataType: dataType.varchar,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: true,
                    unique: true,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 2,
                    name: 'label',
                    label: 'Label',
                    inputType: inputType.shortText,
                    dataType: dataType.varchar,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: true,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 2,
                    name: 'description',
                    label: 'Description',
                    inputType: inputType.longText,
                    dataType: dataType.text,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: false,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 3,
                    name: 'id',
                    label: 'ID',
                    inputType: inputType.number,
                    dataType: dataType.integer,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: true,
                    notNull: true,
                    unique: true,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 3,
                    name: 'label',
                    label: 'Label',
                    inputType: inputType.shortText,
                    dataType: dataType.varchar,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: true,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 3,
                    name: 'tree',
                    label: 'Tree',
                    inputType: inputType.code,
                    dataType: dataType.json,
                    tableRef: null,
                    tableRefKey: null,
                    tableRefName: null,
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: false,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
                {
                    moduleId: 3,
                    name: 'roleId',
                    label: 'Role ID',
                    inputType: inputType.number,
                    dataType: dataType.integer,
                    tableRef: 'Roles',
                    tableRefKey: 'id',
                    tableRefName: 'label',
                    tableRefAlias: null,
                    tableRefFilter: null,
                    regex: null,
                    multiSelect: false,
                    identity: false,
                    notNull: true,
                    unique: false,
                    createdAt: now,
                    updatedAt: now,
                },
            ],
            {},
        );
    },

    async down(queryInterface) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
        await queryInterface.bulkDelete('Fields', null, {});
    },
};
